### ISSUE TITLE
Template Listener breaks boxes of other types

### ISSUE THREAD

**Issue by dtdesign** [xXSchrandXx/de.xxschrandxx.wsc.minecraft-profile#3]
The template listener is executed for every box that has conditions, but will cause an error because the template variables are not present. In fact, this shouldn’t even use a template listener in the first place and instead register itself as a proper condition through the object type definition.

**Comment by xXSchrandXx** [comment]
Removed templateListener (https://github.com/xXSchrandXx/de.xxschrandxx.wsc.minecraft-profile/commit/5d4853801d7d07db11248ca4b51e05e69e41425a) and switched to `isset` (https://github.com/xXSchrandXx/de.xxschrandxx.wsc.minecraft-profile/commit/8850469a249670c453de02e5d15f80eb9fa58c01).
